// Code generated by yago. DO NOT EDIT.
package main // import "github.com/goees/yago/example"

import (
	"github.com/goees/yago"

	_ "github.com/goees/yago/example/app/route"
)

func main() {
	yago.NewCmd().RunCmd()
}
